/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsulanBukuRouteImport } from './routes/usulan-buku'
import { Route as StatusRouteImport } from './routes/status'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AksesInternalRouteImport } from './routes/akses-internal'
import { Route as AjukanRouteImport } from './routes/ajukan'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DokumenIdRouteImport } from './routes/dokumen.$id'
import { Route as AdminUsulanBukuRouteImport } from './routes/admin/usulan-buku'
import { Route as AdminPengajuanRouteImport } from './routes/admin/pengajuan'
import { Route as DokumenIdPreviewRouteImport } from './routes/dokumen.$id.preview'

const UsulanBukuRoute = UsulanBukuRouteImport.update({
  id: '/usulan-buku',
  path: '/usulan-buku',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AksesInternalRoute = AksesInternalRouteImport.update({
  id: '/akses-internal',
  path: '/akses-internal',
  getParentRoute: () => rootRouteImport,
} as any)
const AjukanRoute = AjukanRouteImport.update({
  id: '/ajukan',
  path: '/ajukan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DokumenIdRoute = DokumenIdRouteImport.update({
  id: '/dokumen/$id',
  path: '/dokumen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsulanBukuRoute = AdminUsulanBukuRouteImport.update({
  id: '/usulan-buku',
  path: '/usulan-buku',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPengajuanRoute = AdminPengajuanRouteImport.update({
  id: '/pengajuan',
  path: '/pengajuan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DokumenIdPreviewRoute = DokumenIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DokumenIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/ajukan': typeof AjukanRoute
  '/akses-internal': typeof AksesInternalRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/usulan-buku': typeof UsulanBukuRoute
  '/admin/pengajuan': typeof AdminPengajuanRoute
  '/admin/usulan-buku': typeof AdminUsulanBukuRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dokumen/$id/preview': typeof DokumenIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajukan': typeof AjukanRoute
  '/akses-internal': typeof AksesInternalRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/usulan-buku': typeof UsulanBukuRoute
  '/admin/pengajuan': typeof AdminPengajuanRoute
  '/admin/usulan-buku': typeof AdminUsulanBukuRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dokumen/$id/preview': typeof DokumenIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/ajukan': typeof AjukanRoute
  '/akses-internal': typeof AksesInternalRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/usulan-buku': typeof UsulanBukuRoute
  '/admin/pengajuan': typeof AdminPengajuanRoute
  '/admin/usulan-buku': typeof AdminUsulanBukuRoute
  '/dokumen/$id': typeof DokumenIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dokumen/$id/preview': typeof DokumenIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajukan'
    | '/akses-internal'
    | '/login'
    | '/status'
    | '/usulan-buku'
    | '/admin/pengajuan'
    | '/admin/usulan-buku'
    | '/dokumen/$id'
    | '/admin/'
    | '/dokumen/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajukan'
    | '/akses-internal'
    | '/login'
    | '/status'
    | '/usulan-buku'
    | '/admin/pengajuan'
    | '/admin/usulan-buku'
    | '/dokumen/$id'
    | '/admin'
    | '/dokumen/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajukan'
    | '/akses-internal'
    | '/login'
    | '/status'
    | '/usulan-buku'
    | '/admin/pengajuan'
    | '/admin/usulan-buku'
    | '/dokumen/$id'
    | '/admin/'
    | '/dokumen/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AjukanRoute: typeof AjukanRoute
  AksesInternalRoute: typeof AksesInternalRoute
  LoginRoute: typeof LoginRoute
  StatusRoute: typeof StatusRoute
  UsulanBukuRoute: typeof UsulanBukuRoute
  DokumenIdRoute: typeof DokumenIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usulan-buku': {
      id: '/usulan-buku'
      path: '/usulan-buku'
      fullPath: '/usulan-buku'
      preLoaderRoute: typeof UsulanBukuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akses-internal': {
      id: '/akses-internal'
      path: '/akses-internal'
      fullPath: '/akses-internal'
      preLoaderRoute: typeof AksesInternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajukan': {
      id: '/ajukan'
      path: '/ajukan'
      fullPath: '/ajukan'
      preLoaderRoute: typeof AjukanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dokumen/$id': {
      id: '/dokumen/$id'
      path: '/dokumen/$id'
      fullPath: '/dokumen/$id'
      preLoaderRoute: typeof DokumenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usulan-buku': {
      id: '/admin/usulan-buku'
      path: '/usulan-buku'
      fullPath: '/admin/usulan-buku'
      preLoaderRoute: typeof AdminUsulanBukuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pengajuan': {
      id: '/admin/pengajuan'
      path: '/pengajuan'
      fullPath: '/admin/pengajuan'
      preLoaderRoute: typeof AdminPengajuanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dokumen/$id/preview': {
      id: '/dokumen/$id/preview'
      path: '/preview'
      fullPath: '/dokumen/$id/preview'
      preLoaderRoute: typeof DokumenIdPreviewRouteImport
      parentRoute: typeof DokumenIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPengajuanRoute: typeof AdminPengajuanRoute
  AdminUsulanBukuRoute: typeof AdminUsulanBukuRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPengajuanRoute: AdminPengajuanRoute,
  AdminUsulanBukuRoute: AdminUsulanBukuRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DokumenIdRouteChildren {
  DokumenIdPreviewRoute: typeof DokumenIdPreviewRoute
}

const DokumenIdRouteChildren: DokumenIdRouteChildren = {
  DokumenIdPreviewRoute: DokumenIdPreviewRoute,
}

const DokumenIdRouteWithChildren = DokumenIdRoute._addFileChildren(
  DokumenIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AjukanRoute: AjukanRoute,
  AksesInternalRoute: AksesInternalRoute,
  LoginRoute: LoginRoute,
  StatusRoute: StatusRoute,
  UsulanBukuRoute: UsulanBukuRoute,
  DokumenIdRoute: DokumenIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
